<template>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="204px" height="204px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <rect x="17" y="41" width="16" height="18" fill="#58acf4">
            <animate attributeName="y" repeatCount="indefinite" dur="0.5813953488372093s" calcMode="spline" keyTimes="0;0.5;1" values="35.6;41;41" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.11627906976744187s"></animate>
            <animate attributeName="height" repeatCount="indefinite" dur="0.5813953488372093s" calcMode="spline" keyTimes="0;0.5;1" values="28.8;18;18" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.11627906976744187s"></animate>
        </rect>
        <rect x="42" y="41" width="16" height="18" fill="#105edd">
            <animate attributeName="y" repeatCount="indefinite" dur="0.5813953488372093s" calcMode="spline" keyTimes="0;0.5;1" values="36.95;41;41" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.058139534883720936s"></animate>
            <animate attributeName="height" repeatCount="indefinite" dur="0.5813953488372093s" calcMode="spline" keyTimes="0;0.5;1" values="26.1;18;18" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.058139534883720936s"></animate>
        </rect>
        <rect x="67" y="41" width="16" height="18" fill="#0b3075">
            <animate attributeName="y" repeatCount="indefinite" dur="0.5813953488372093s" calcMode="spline" keyTimes="0;0.5;1" values="36.95;41;41" keySplines="0 0.5 0.5 1;0 0.5 0.5 1"></animate>
            <animate attributeName="height" repeatCount="indefinite" dur="0.5813953488372093s" calcMode="spline" keyTimes="0;0.5;1" values="26.1;18;18" keySplines="0 0.5 0.5 1;0 0.5 0.5 1"></animate>
        </rect>
        <!-- [ldio] generated by https://loading.io/ -->
    </svg>
</template>

<script>
    export default {
        name: "PulseLoading"
    }
</script>

<style scoped>

</style>
